apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: plasseringsspillet
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: plasseringsspillet
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Bot
        email: flux@stackunderflow.no
      messageTemplate: |
        Automated image update
    push:
      branch: main
