// Curated games ("themes"). Each is one game with two arbitrary numeric axes.
// Values are approximate but plausible — this is a party game.

import type { Theme } from "~/game/types";

export const THEMES: Theme[] = [
  {
    id: "test",
    name: "Testdata",
    description:
      "Liten datasett for testing. Enkle, forutsigbare verdier på begge akser.",
    xAxis: { label: "X-verdi", scale: "linear" },
    yAxis: { label: "Y-verdi", scale: "linear" },
    seedAnchorIds: ["t-a", "t-c", "t-e"],
    cards: [
      { id: "t-a", title: "A", x: 1, y: 1, blurb: "Test A: x=1, y=1." },
      { id: "t-b", title: "B", x: 2, y: 2, blurb: "Test B: x=2, y=2." },
      { id: "t-c", title: "C", x: 3, y: 3, blurb: "Test C: x=3, y=3." },
      { id: "t-d", title: "D", x: 4, y: 4, blurb: "Test D: x=4, y=4." },
      { id: "t-e", title: "E", x: 5, y: 5, blurb: "Test E: x=5, y=5." },
    ],
  },
  {
    id: "ol-utovere",
    name: "Norske OL-utøvere",
    description: "Plasser utøveren etter antall OL-gull og høyde.",
    xAxis: { label: "Antall OL-gull", scale: "linear" },
    yAxis: { label: "Høyde", unit: "cm", scale: "linear" },
    seedAnchorIds: ["sonja-henie", "kjetil-andre-aamodt", "marit-bjorgen"],
    cards: [
      {
        id: "marit-bjorgen",
        title: "Marit Bjørgen",
        x: 8,
        y: 168,
        blurb: "Langrennsløper, 8 OL-gull — tidenes mest vinnende vinter-OL-utøver.",
      },
      {
        id: "ole-einar-bjorndalen",
        title: "Ole Einar Bjørndalen",
        x: 8,
        y: 178,
        blurb: "Skiskytterkongen med 8 OL-gull.",
      },
      {
        id: "bjorn-daehlie",
        title: "Bjørn Dæhlie",
        x: 8,
        y: 186,
        blurb: "Langrennsløper med 8 OL-gull.",
      },
      {
        id: "therese-johaug",
        title: "Therese Johaug",
        x: 4,
        y: 167,
        blurb: "Langrennsløper, 4 OL-gull.",
      },
      {
        id: "johannes-thingnes-bo",
        title: "Johannes Thingnes Bø",
        x: 5,
        y: 184,
        blurb: "Skiskytter med 5 OL-gull.",
      },
      {
        id: "sonja-henie",
        title: "Sonja Henie",
        x: 3,
        y: 158,
        blurb: "Kunstløper, 3 OL-gull på 1920- og 30-tallet.",
      },
      {
        id: "aksel-lund-svindal",
        title: "Aksel Lund Svindal",
        x: 2,
        y: 189,
        blurb: "Alpinist med 2 OL-gull.",
      },
      {
        id: "kjetil-andre-aamodt",
        title: "Kjetil André Aamodt",
        x: 4,
        y: 176,
        blurb: "Alpinist med 4 OL-gull.",
      },
      {
        id: "lasse-kjus",
        title: "Lasse Kjus",
        x: 1,
        y: 180,
        blurb: "Alpinist med 1 OL-gull.",
      },
      {
        id: "petter-northug",
        title: "Petter Northug",
        x: 2,
        y: 184,
        blurb: "Langrennsløper med 2 OL-gull.",
      },
      {
        id: "kjetil-jansrud",
        title: "Kjetil Jansrud",
        x: 1,
        y: 183,
        blurb: "Alpinist med 1 OL-gull.",
      },
      {
        id: "vegard-ulvang",
        title: "Vegard Ulvang",
        x: 3,
        y: 178,
        blurb: "Langrennsløper med 3 OL-gull.",
      },
      {
        id: "stein-eriksen",
        title: "Stein Eriksen",
        x: 1,
        y: 180,
        blurb: "Alpinpioner med 1 OL-gull (1952).",
      },
      {
        id: "hjalmar-andersen",
        title: "Hjalmar Andersen",
        x: 3,
        y: 178,
        blurb: "Skøyteløper med 3 OL-gull (1952).",
      },
    ],
  },
  {
    id: "norske-filmer",
    name: "Norske filmer",
    description: "Plasser filmen etter utgivelsesår og IMDb-score.",
    xAxis: { label: "Utgivelsesår", scale: "linear" },
    yAxis: { label: "IMDb-score", scale: "linear" },
    seedAnchorIds: ["flaklypa-grand-prix", "elling", "kongens-nei"],
    cards: [
      {
        id: "flaklypa-grand-prix",
        title: "Flåklypa Grand Prix",
        x: 1975,
        y: 8.2,
        blurb: "Ivo Caprinos dukkefilm-klassiker fra 1975.",
      },
      {
        id: "veiviseren",
        title: "Veiviseren",
        x: 1987,
        y: 7.4,
        blurb: "Samisk eventyrfilm, Oscar-nominert (1987).",
      },
      {
        id: "insomnia-1997",
        title: "Insomnia",
        x: 1997,
        y: 7.2,
        blurb: "Erik Skjoldbjærgs thriller med Stellan Skarsgård (1997).",
      },
      {
        id: "elling",
        title: "Elling",
        x: 2001,
        y: 7.5,
        blurb: "Oscar-nominert komidrama (2001).",
      },
      {
        id: "buddy",
        title: "Buddy",
        x: 2003,
        y: 7.2,
        blurb: "Feelgood-komedie med Aksel Hennie (2003).",
      },
      {
        id: "hawaii-oslo",
        title: "Hawaii, Oslo",
        x: 2004,
        y: 7.4,
        blurb: "Ensemblefilm av Erik Poppe (2004).",
      },
      {
        id: "dod-sno",
        title: "Død snø",
        x: 2009,
        y: 6.4,
        blurb: "Zombie-nazi-grøsser (2009).",
      },
      {
        id: "max-manus",
        title: "Max Manus",
        x: 2008,
        y: 7.3,
        blurb: "Krigsdrama om motstandsmannen (2008).",
      },
      {
        id: "trolljegeren",
        title: "Trolljegeren",
        x: 2010,
        y: 7.0,
        blurb: "Found-footage om troll (2010).",
      },
      {
        id: "hodejegerne",
        title: "Hodejegerne",
        x: 2011,
        y: 7.5,
        blurb: "Thriller etter Jo Nesbøs roman (2011).",
      },
      {
        id: "kon-tiki",
        title: "Kon-Tiki",
        x: 2012,
        y: 7.2,
        blurb: "Oscar-nominert om Thor Heyerdahls ferd (2012).",
      },
      {
        id: "kongens-nei",
        title: "Kongens nei",
        x: 2016,
        y: 7.4,
        blurb: "Drama om kong Haakon i 1940 (2016).",
      },
      {
        id: "kaptein-sabeltann",
        title: "Kaptein Sabeltann",
        x: 2014,
        y: 5.6,
        blurb: "Familiefilm om sjørøveren (2014).",
      },
      {
        id: "the-wave",
        title: "Bølgen",
        x: 2015,
        y: 6.9,
        blurb: "Katastrofefilm om en fjellskredtsunami (2015).",
      },
    ],
  },
  {
    id: "norske-byer",
    name: "Norske byer",
    description: "Plasser byen etter grunnleggingsår og innbyggertall.",
    xAxis: { label: "Grunnlagt (år)", scale: "linear" },
    yAxis: { label: "Innbyggere", scale: "log" },
    seedAnchorIds: ["oslo", "hamar", "tromso"],
    cards: [
      {
        id: "oslo",
        title: "Oslo",
        x: 1048,
        y: 700000,
        blurb: "Hovedstaden, grunnlagt ca. 1048.",
      },
      {
        id: "bergen",
        title: "Bergen",
        x: 1070,
        y: 290000,
        blurb: "Grunnlagt ca. 1070.",
      },
      {
        id: "trondheim",
        title: "Trondheim",
        x: 997,
        y: 210000,
        blurb: "Grunnlagt 997 av Olav Tryggvason.",
      },
      {
        id: "stavanger",
        title: "Stavanger",
        x: 1125,
        y: 145000,
        blurb: "Bystatus ca. 1125 (domkirken).",
      },
      {
        id: "tromso",
        title: "Tromsø",
        x: 1794,
        y: 78000,
        blurb: "Kjøpstad 1794.",
      },
      {
        id: "kristiansand",
        title: "Kristiansand",
        x: 1641,
        y: 115000,
        blurb: "Grunnlagt 1641 av Christian IV.",
      },
      {
        id: "drammen",
        title: "Drammen",
        x: 1811,
        y: 105000,
        blurb: "Bystatus 1811.",
      },
      {
        id: "alesund",
        title: "Ålesund",
        x: 1848,
        y: 67000,
        blurb: "Kjøpstad 1848.",
      },
      {
        id: "bodo",
        title: "Bodø",
        x: 1816,
        y: 55000,
        blurb: "Kjøpstad 1816.",
      },
      {
        id: "hamar",
        title: "Hamar",
        x: 1849,
        y: 33000,
        blurb: "Bystatus 1849 (gammel bispeby fra 1152).",
      },
      {
        id: "fredrikstad",
        title: "Fredrikstad",
        x: 1567,
        y: 85000,
        blurb: "Grunnlagt 1567 av Fredrik II.",
      },
      {
        id: "tonsberg",
        title: "Tønsberg",
        x: 871,
        y: 57000,
        blurb: "Regnes som Norges eldste by, ca. 871.",
      },
      {
        id: "skien",
        title: "Skien",
        x: 1000,
        y: 56000,
        blurb: "En av landets eldste byer.",
      },
      {
        id: "molde",
        title: "Molde",
        x: 1742,
        y: 32000,
        blurb: "Kjøpstad 1742.",
      },
    ],
  },
  {
    id: "norske-fjell",
    name: "Norske fjell",
    description: "Plasser fjellet etter høyde og primærfaktor.",
    xAxis: { label: "Høyde", unit: "moh", scale: "linear" },
    yAxis: { label: "Primærfaktor", unit: "m", scale: "linear" },
    seedAnchorIds: ["galdhopiggen", "gaustatoppen", "romsdalshorn"],
    cards: [
      {
        id: "galdhopiggen",
        title: "Galdhøpiggen",
        x: 2469,
        y: 2372,
        blurb: "Norges høyeste fjell, 2469 moh.",
      },
      {
        id: "glittertind",
        title: "Glittertind",
        x: 2452,
        y: 558,
        blurb: "Nest høyest, 2452 moh.",
      },
      {
        id: "store-skagastolstind",
        title: "Store Skagastølstind",
        x: 2405,
        y: 829,
        blurb: "Storen — krevende tindebestigning, 2405 moh.",
      },
      {
        id: "snohetta",
        title: "Snøhetta",
        x: 2286,
        y: 1675,
        blurb: "Dovrefjells høyeste, 2286 moh.",
      },
      {
        id: "store-styggedalstind",
        title: "Store Styggedalstind",
        x: 2387,
        y: 137,
        blurb: "Hurrungane-tind, 2387 moh.",
      },
      {
        id: "gaustatoppen",
        title: "Gaustatoppen",
        x: 1883,
        y: 1217,
        blurb: "Telemarks landemerke, 1883 moh.",
      },
      {
        id: "romsdalshorn",
        title: "Romsdalshorn",
        x: 1550,
        y: 645,
        blurb: "Markant tind i Romsdalen, 1550 moh.",
      },
      {
        id: "stetind",
        title: "Stetind",
        x: 1392,
        y: 1339,
        blurb: "Norges nasjonalfjell, 1392 moh.",
      },
      {
        id: "store-trolltind",
        title: "Store Trolltind",
        x: 1788,
        y: 808,
        blurb: "Høyest i Trolltindene over Trollveggen, 1788 moh.",
      },
      {
        id: "kebnekaise-norge",
        title: "Jiehkkevárri",
        x: 1834,
        y: 1741,
        blurb: "Lyngsalpenes og Troms' høyeste, 1834 moh.",
      },
      {
        id: "store-smortind",
        title: "Store Smørstabbtind",
        x: 2208,
        y: 366,
        blurb: "Smørstabbreen-massivet, 2208 moh.",
      },
      {
        id: "hardangerjokulen",
        title: "Hardangerjøkulen",
        x: 1863,
        y: 1119,
        blurb: "Isbredekt topp på Hardangervidda, 1863 moh.",
      },
      {
        id: "snota",
        title: "Snota",
        x: 1668,
        y: 1116,
        blurb: "Trollheimen-tind, 1668 moh.",
      },
      {
        id: "falketind",
        title: "Falketind",
        x: 2067,
        y: 380,
        blurb: "Jotunheimen, 2067 moh.",
      },
    ],
  },
];

export function getTheme(id: string): Theme | undefined {
  return THEMES.find((t) => t.id === id);
}
